apiVersion: v1
kind: Service
metadata:
  name: apache-ranger
  labels:
    app: apache-ranger
spec:
  ports:
    - port: 6080
      targetPort: 6080
      protocol: TCP
      name: http
  selector:
    app: apache-ranger
status:
  loadBalancer: {}
